apiVersion: v1
kind: ResourceQuota
metadata:
  name: jenkins-resourcequota
  namespace: my-jenkins
spec:
  hard:
    pods: "6"
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
