apiVersion: ""
generated: "0001-01-01T00:00:00Z"
repositories:
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: aws-efs-csi-driver
  pass_credentials_all: false
  password: ""
  url: https://kubernetes-sigs.github.io/aws-efs-csi-driver/
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: aws-ebs-csi-driver
  pass_credentials_all: false
  password: ""
  url: https://kubernetes-sigs.github.io/aws-ebs-csi-driver/
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: istio
  pass_credentials_all: false
  password: ""
  url: https://istio-release.storage.googleapis.com/charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: jenkins-helm-local
  pass_credentials_all: false
  password: cmVmdGtuOjAxOjE3NzY4NTM0MDQ6MnJCUjg5M2xUYjR1VDZZdTVFMmMzOG14MWdP
  url: https://trialp0rpyr.jfrog.io/artifactory/api/helm/jenkins-helm-local
  username: vineethmuntamadugu@gmail.com
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: argo-cd
  pass_credentials_all: false
  password: ""
  url: https://argoproj.github.io/argo-helm
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: argo
  pass_credentials_all: false
  password: ""
  url: https://argoproj.github.io/argo-helm
  username: ""
